### ISSUE TITLE
Find way to select Space Station by actually changing the video src from "" to the video path

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/CadenceRadio#24]

**Comment by za419** [comment]
My local copy of Cadence doesn't actually start loading the video until after selecting the space station theme, possibly due at least in part to the fix for #28 I implemented in 931bbd7f5836f1bbef90cdd3e36e01750208c711.

I'll still implement my proposed fix though.

**Comment by za419** [comment]
No one sees the first commit that I replaced because I messed up a pull request. In fact, its not even there. I promise.

**Comment by kenellorando** [comment]
A lot of sneakiness going on in this repository these days
