### ISSUE TITLE
Space Station doesn't work - IMPORTANT

### ISSUE THREAD

**Issue by za419** [kenellorando/CadenceRadio#39]
The space station theme changes the site subtitle correctly, but the background is black. Chicago evening and Cyberpunk bartender work correctly.

These symptoms have been replicated on the following: Edge/Chrome on Windows 10 (same device), Chrome on two different Android devices

**Comment by za419** [comment]
Requesting the theme results in a small (<512B) network response for iss.mp4, with an empty response (reported by Chrome). My current running theory is that a git-lfs pointer somehow made it onto the production server

**Comment by za419** [comment]
Now working.

**Comment by kenellorando** [comment]
Not sure what caused this. iss.mp4 on my local directory and thus the server directory, was only a few hundred bytes. The correct file size is upwards of 40MB
