### ISSUE TITLE
Try using a css zoom

### ISSUE THREAD

**Issue by kenellorando** [kenellorando/CadenceRadio#45]

**Comment by za419** [comment]
For...?

**Comment by kenellorando** [comment]
I forgot my laptop zooms everything at 150% because of the screen size. So I didn't realize that while developing, the player looks much more zoomed out than intended on everybody elses' screens. 

I was looking for a way to scale everything from the title to the volume bar to always take up most of the screen height, even no matter the screen size or how much the OS scales.

**Comment by za419** [comment]
Oh. It's always looked fine to me...

I see:
![image](https://cloud.githubusercontent.com/assets/15851480/24940350/33e6740c-1f08-11e7-9384-3e836b32a4fd.png)

You see.... 
![image](https://cloud.githubusercontent.com/assets/15851480/24940365/3eafbc18-1f08-11e7-9616-19f6500a02c7.png)

That? Kind of?

I guess one could amend the meta viewport tag to include `height=device-height`, I think that would affect that... But not sure how it might interact with the width et cetera, or even how supported it is. But honestly it's looked fine to me.

If you want to be really anal about it, JS should do the trick...
